#!/usr/bin/env python3

import os
import cv2
import time
import boto3
from PIL import Image, ImageDraw, ExifTags, ImageColor
from detect_labels_local_file import detectLabels

directory = time.strftime("%Y%m%d")
parent_directory = "/home/pi/Pictures/"
timestr = time.strftime("%Y%m%d_%H%M%S")
path = os.path.join(parent_directory, directory)
if not path:
  os.mkdir(path)

frame_rate = 0.25
prev = 0
img_counter = 1

cv = cv2.VideoCapture(0)
cv.set(3,640)
cv.set(4,480)

while True:
  ret,frame = cv.read()
  half = cv2.resize(frame, (0,0), fx=0.4, fy=0.4)
  time_elapsed = time.time() - prev

  if time_elapsed > 1./frame_rate:
    prev = time.time()
    cv2.imshow("cam",half)
    img_name = path+"/IMG_{}_{}.jpg".format(timestr,img_counter)
    cv2.imwrite(img_name,half)
    img_counter+=1
    labels=detectLabels(img_name)
    print(labels)

  k = cv2.waitKey(1)
  if k%256 == 27:
    break

cv.release()
cv2.destroyAllWindows()
