#!/usr/bin/env python3

import struct
import pvporcupine
import pyaudio
from generateSpeech import generateSpeech

try:
  py_audio = pyaudio.PyAudio()
  handle = pvporcupine.create(keywords=["porcupine"])
  audio_stream = py_audio.open(
                   rate=handle.sample_rate,
                   channels=1,
                   format=pyaudio.paInt16,
                   input=True,
                   frames_per_buffer=handle.frame_length)

  while True:
    pcm = audio_stream.read(handle.frame_length)
    audio_frame = struct.unpack_from("h" * handle.frame_length, pcm)
    keyword_index = handle.process(audio_frame)

    if keyword_index >= 0:
      print("Detected")
      generateSpeech("I can hear you")

except KeyboardInterrupt:
  print("Done")
