#!/usr/bin/env python3

import cv2
import time

frame_rate = 30
prev = 0

cv = cv2.VideoCapture(0)
cv.set(3,640)
cv.set(4,480)

while True:
  ret,frame = cv.read()
  half = cv2.resize(frame, (0,0), fx=0.4, fy=0.4)
  time_elapsed = time.time() - prev
  if time_elapsed > 1./frame_rate:
    prev = time.time()
    cv2.imshow("cam",half)

  k = cv2.waitKey(1)
  if k%256 == 27:
    break

cv.release()
cv2.destroyAllWindows()
