#!/usr/bin/env python3

import cv2
import time
import boto3
from detect_labels_local_file import detect_labels_local_file
from detect_faces_local_file import detect_faces_local_file

timestr = time.strftime("%Y%m%d_%H%M%S")
path = "/home/pi/Pictures/"

capture = cv2.VideoCapture(0)

while True:
  ret, frame = capture.read()
  image = cv2.resize(frame, (0,0), fx=0.4, fy=0.4)

  cv2.imshow("Capture", image)

  k = cv2.waitKey(1)
  if k%256 == 27: #Esc Key
    break
  elif k%256 == 32: #Space Bar
    img_name = path+"IMG_{}.jpg".format(timestr)
    cv2.imwrite(img_name, image)

    labels = detect_labels_local_file(img_name)
    #print(labels)
    faces = detect_faces_local_file(img_name)
    print(faces)

capture.release()
cv2.destroyAllWindows()
